List of countries (Component)
deinsoftware/fun-with-flags pull request #22
Opened 2023-07-20 01:47 UTC by MrRedu

2023-07-22 22:14 UTC, equiman commented on src/app/components/ListOfCoutries/MoreCountries.tsx
> +  // const [timeZones, setTimeZones] = useState(timeZone)
Eliminar este código comentado

2023-07-22 22:14 UTC, equiman commented on src/app/components/ListOfCoutries/SelectTimeZone.tsx
> +  // const [countries, setCountries] = useState(data)
Eliminar este código comentado

2023-07-22 22:14 UTC, equiman commented on src/app/components/ListOfCoutries/SelectTimeZoneOption.tsx
> +  // const {id, timeZone, countryCode, regionName} = country;
Eliminar código comentado

2023-07-22 22:14 UTC, equiman commented on src/app/components/ListOfCoutries/SelectTimeZoneOption.tsx
> +  // const [countries, setCountries] = useState(data)
Eliminar código comentado

2023-07-22 22:14 UTC, equiman commented on src/app/create-event/page.tsx
> +// export const metadata = {
Este código si debe estar comentado, o es para que actualice los metadatos?

2023-07-23 14:38 UTC, MrRedu commented on src/app/create-event/page.tsx
> +// export const metadata = {
Este fragmento de código estaba comentado porque no se puede exportar metadata desde un componente que se renderiza en el cliente, pero ya des-comenté esa parte y cambié el 'use client' al componente que realmente lo necesita.

✔ Comentarios eliminados
✔ El blanco absoluto permanece por el estilo del loginButton de Google *(https://developers.google.com/identity/branding-guidelines?hl=es-419)*
✔export metadata - Solucionado

2023-07-23 15:04 UTC, equiman commented
You need to include the changes on `dev` branch with `git pull origin dev` to solve the conflicts.

2023-07-23 23:47 UTC, equiman requested changes

2023-07-23 23:47 UTC, equiman commented on src/app/api/timezones/route.ts
> +      .sort((a, z) => a?.regionName.localeCompare(z?.regionName))
To correct the TS error, use:

```
.sort((a, z) => (a?.regionName ?? '').localeCompare(z?.regionName ?? ''))
```

2023-07-25 03:17 UTC, equiman approved these changes

2023-07-25 03:17 UTC, merged