Share events
deinsoftware/fun-with-flags pull request #37
Opened 2023-07-27 02:37 UTC by Alexis033

Add timeZoneContext with method addTimeZone, deleteTimeZone and setOriginDate.

2023-07-27 19:05 UTC, equiman requested changes

2023-07-27 19:05 UTC, equiman commented on src/app/components/molecules/country-combo/useGetInfoDates.ts
> +type Format = {
Este tipo lo podrías agregar en el archivo `events.types.ts` para que quede junto con los otros tipos realacionados? 

Podría ser debajo de `export type Zone = {` y creo que sería más nemotécnico llamarlo `TimeFormat`. Una vez definido ahi reemplazar todas las coincidencias en los otros archivos con `12 | 24` por el nuevo tipo.

2023-07-27 22:05 UTC, equiman requested changes

2023-07-27 22:05 UTC, equiman commented on src/helpers/get-country-code.ts
> +    const response = await fetch(`${process.env.API_URL}/api/timezones/${zone}`)
Ya existe una variable de entorno para la URL del servidor:

`NEXT_PUBLIC_API_URL="http://localhost:3000"`

2023-07-27 22:47 UTC, Alexis033 commented on src/helpers/get-country-code.ts
> +    const response = await fetch(`${process.env.API_URL}/api/timezones/${zone}`)
cierto, pero igual no soluciona el problema, porque cuando hace el build el host siempre cambia.

2023-07-27 23:39 UTC, equiman commented on src/helpers/get-country-code.ts
> +    const response = await fetch(`${process.env.API_URL}/api/timezones/${zone}`)
recuerda también porfa todas las peticiones al api, se deben hacer desde la carpeta services, para que los tengamos como una capa aparte.

La URL del build a prod se alamacena y se cambia en vercel. Ahora en la reu les muestro como se define.

2023-07-28 20:20 UTC, MrRedu approved these changes

2023-07-30 15:20 UTC, equiman requested changes

2023-07-30 15:20 UTC, equiman commented on src/app/components/molecules/country-combo/useGetInfoDates.ts
> +      const valueList: ZoneList | null = timeZones
code smell, no se debe usar ternary operators cuando hay lógica dentro de una de las condiciones.

2023-07-30 15:20 UTC, equiman commented on src/helpers/events.types.ts
> +export type TimeFormat = {
En este caso no necesita un subtipo, se puede definir directamente como `export type TimeFormat = 12 | 24`

2023-07-30 15:20 UTC, equiman commented on src/helpers/share-events.test.ts
Excelente que le hayas incluido también pruebas unitarias 👍

2023-07-30 15:20 UTC, equiman commented on src/services/timezones.ts
falta incluirle el abort contol

2023-07-30 21:25 UTC, Alexis033 commented on src/helpers/events.types.ts
> +export type TimeFormat = {
mm creo que no puedo usarlo así, porque es un tipo que uso para un componente que recibe los parámetros como objetos.

2023-07-31 02:04 UTC, equiman commented on src/helpers/events.types.ts
> +export type TimeFormat = {
Oks, mañana lo miramos

2023-08-01 01:16 UTC, MrRedu approved these changes

2023-08-01 01:17 UTC, equiman approved these changes

2023-08-01 01:17 UTC, merged